[package]
name = "yvh-api"
version = "0.1.0"
authors = ["Anler Hernández Peral <inbox.anler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["yvh"]

[dependencies]
yvh = { path = "./yvh" }
